name: Sync to text repo

on:
  push:
    branches:
      - main  # or whatever your default branch is named

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout textMain
      uses: actions/checkout@v2
      with:
        path: textMain

    - name: Checkout text repo
      uses: actions/checkout@v2
      with:
        repository: IMOitself/text
        token: ${{ secrets.PAT_TOKEN }}
        path: text

    - name: Sync changes
      run: |
        cd text
        rm -rf app/src/main
        cp -R ../textMain app/src/main
        git config user.name IMOitself
        git config user.email russjonn@gmail.com
        git add app/src/main
        git commit -m "Sync changes from textMain" || echo "No changes to commit"
        git push